version: '2'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  api:
    build:
      context: ./http-server
      dockerfile: Dockerfile
    image: api
    expose:
      - "8080"
    environment:
      - VIRTUAL_HOST=server-api.test
      - VIRTUAL_PORT=8080
